apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: azeroth
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: ghcr.io/vmaleze/cilium-hands-on/none
          name: app
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
