apiVersion: apps/v1
kind: Deployment
metadata:
  name: unit
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: ghcr.io/vmaleze/cilium-hands-on/unit:1.0.0
          name: unit
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
